model:
  name: simple
  input_dim: 10
  hidden_dim: 32
  output_dim: 2

dataset:
  num_samples: 1000
  input_dim: 10

training:
  epochs: 5
  lr: 0.01
  batch_size: 64

output:
  metrics_path: results/train_metrics.json
